### ISSUE TITLE
KeyError: BlazeDataSet_0<US>.value::float64 when running minimal example

### ISSUE THREAD

**Issue by twiecki** [marketneutral/alphatools#6]
I'm trying to run https://github.com/marketneutral/alphatools/blob/master/notebooks/pipeline-blaze-minimal.ipynb which runs fine until the pipeline call where I get: `KeyError: BlazeDataSet_0<US>.value::float64`

**Comment by twiecki** [comment]
I figured it out:
```
ds = from_blaze(
    expr,
    no_deltas_rule='ignore',
    no_checkpoints_rule='ignore',
    loader=my_blaze_loader,
    missing_values={'index': -1},
    domain=US_EQUITIES
)
```

Needs a domain. Now running into:
```
TypeError: Cannot change data-type for object array.
```

**Comment by marketneutral** [comment]
I've only tested with zipline 1.3. It's probably not good form, but I use an [install bash script](https://github.com/marketneutral/alphatools/blob/master/install_stable.sh) to set everything in a conda environment up and enforce various dependencies. I haven't worked with this project in almost two years so surely many other packages (incl. the Python language) have advanced.
